# Generated by Django 5.0.2 on 2024-03-03 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0002_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="avatars",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
                verbose_name="Avatar",
            ),
        ),
    ]
