# Generated by Django 5.0.2 on 2024-03-09 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0009_alter_customuser_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                max_length=300,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Profile",
            ),
        ),
    ]
